_BASE_: "Base-CenterNet2.yaml"
MODEL:
  BACKBONE:
    NAME: "build_p37_fcos_dla_bifpn_backbone"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 5
    NUM_BIFPN: 3
  WEIGHTS: "/archive/mingzhen/model/handcnn/dla_ct2/model_final.pth"
  CENTERNET:
    POST_NMS_TOPK_TEST: 128
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
  ROI_HEADS:
    NUM_CLASSES: 1
SOLVER:
  MAX_ITER: 30000
  BASE_LR: 0.0002
  IMS_PER_BATCH: 32
  CHECKPOINT_PERIOD: 5000
  STEPS: (20000, )
TEST:
  EVAL_PERIOD: 20000
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
  MIN_SIZE_TEST: 608
  MAX_SIZE_TEST: 900
DATASETS:
    TRAIN: ("hands_train",)
    TEST: ("hands_test",)

OUTPUT_DIR: "/archive/mingzhen/model/handcnn/dla_ct2_yt"
