_BASE_: "CenterNet.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN_siamese"
  BACKBONE:
    NAME: "build_siamese_p37_fcos_dla_bifpn_backbone"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 5
    NUM_BIFPN: 3
  WEIGHTS: "/archive/mingzhen/model/handcnn/dla_ct2/model_0039999.pth"
  PIXEL_MEAN: [113.03306, 104.3256, 97.46098]
  PIXEL_STD: [68.95043, 67.54691, 66.24383]
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
  ROI_HEADS:
    NAME: TrackingCascadeROIHeads
    NUM_CLASSES: 1
    NMS_THRESH_TEST: 0.3
SOLVER:
  MAX_ITER: 12000
  BASE_LR: 0.0005
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 2000
  STEPS: (10000, )
TEST:
  EVAL_PERIOD: 200000
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 832
  SCALE_RANGE: (1,1) 
  RANDOM_FLIP: "horizontal"
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1080
DATASETS:
  TRAIN: ("hands_train",)
  TEST: ("hands_test",)
OUTPUT_DIR: "/archive/mingzhen/model/handcnn/yt_trk_new"